config/routes.rb
Rails.application.routes.draw do
  root to: 'topics#index'

  resources :topics
  get 'topics/new/:topic_id', to: 'topics#new', as: 'new_child_topic'

  resources :forum_threads do
    end
  resources :black_lists
end

app/models/black_list.rb
class BlackList < ActiveRecord::Base
  validates :word, 
            presence: {
              message: I18n.translate('black_list.message.error.presence')
            }

  def self.sanitize(string, mask)
    black_list = FinderBlackListService.all
    black_list.each do |bl|
      string.gsub!(/\b#{bl.word}\b/i, mask)
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  TOPIC_STATUS = %w(active inactive)
  LIMIT_PER_PAGE = 10

  belongs_to :topic, class_name: 'Topic'
  has_many :topics, class_name: 'Topic'

  validates :description,
            :status,
            presence: {
              message: I18n.translate('topic.message.error.presence')
            }

  validates :status,
            inclusion: { in: TOPIC_STATUS }

  validates_with Topic::Validator

  def self.status_collection
    TOPIC_STATUS
  end

  def self.limit_default
    LIMIT_PER_PAGE
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found(message = 'Not found')
    raise ActionController::RoutingError.new(message)
  end
end

app/controllers/black_lists_controller.rb
class BlackListsController < ApplicationController
  before_action :set_black_list, only: [:show, :edit, :update, :destroy]

  def index
    @black_lists = BlackList.all
  end

  def show
  end

  def new
    @black_list = BlackList.new
  end

  def edit
  end

  def create
    @black_list = BlackList.new(black_list_params)

    respond_to do |format|
      if @black_list.save
        format.html { redirect_to @black_list, notice: I18n.translate('black_list.message.success_create') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @black_list.update(black_list_params)
        format.html { redirect_to @black_list, notice: I18n.translate('black_list.message.success_update') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @black_list.destroy
    respond_to do |format|
      format.html { redirect_to black_lists_url, notice: I18n.translate('black_list.message.success_destroy') }
    end
  end

  private
  def set_black_list
    @black_list = BlackList.find(params[:id])
  end

  def black_list_params
    params.require(:black_list).permit(:word)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_parent_topic, only: [:new]
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @total = FinderTopicService.count
    @limit = Topic.limit_default
    @page = params[:page].present? ? params[:page] : 0
    @topics = FinderTopicService.find_by_topic(nil, @limit, @page)
  end

  def show
  end

  def new
    @topic = Topic.new
    @topic.topic = @parent_topic
  end

  def edit
    @parent_topic = @topic.topic
  end

  def create
    @topic = Topic.new(topic_params)
    # @topic.topic = @parent_topic

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_url, notice: I18n.translate('topic.message.success_create') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: I18n.translate('topic.message.success_update') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: I18n.translate('topic.message.success_destroy') }
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def set_parent_topic
    @parent_topic = Topic.find(params[:topic_id]) if params[:topic_id].present?
  end

  def topic_params
    params.require(:topic).permit(:description, :status, :topic_id, :limit, :page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_lists_helper.rb
module BlackListsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def pagination(total, limit, page)
    pages = []
    t = (total.to_f / limit.to_f).ceil
    t.times do |n|
      pages.push n
    end
    select_tag(:p, options_for_select(pages.map { |value| [(value + 1), value] }, selected: page) )
  end
end

app/views/black_lists/_form.html.erb
<%= form_for(@black_list) do |f| %>
  <% if @black_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@black_list.errors.count, t('application.label.error')) %> <%= t('black_list.label.error') %>:</h2>

      <ul>
      <% @black_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/black_lists/edit.html.erb
<h1><%= t('black_list.title.edit') %></h1>

<%= render 'form' %>

<%= link_to t('application.action.show'), @black_list %> |
<%= link_to t('application.action.back'), black_lists_path %>

app/views/black_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('black_list.title.index') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('helpers.label.black_list.word') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @black_lists.each do |black_list| %>
      <tr>
        <td><%= black_list.word %></td>
        <td><%= link_to t('black_list.action.show'), black_list %></td>
        <td><%= link_to t('black_list.action.update'), edit_black_list_path(black_list) %></td>
        <td><%= link_to t('black_list.action.destroy'), black_list, method: :delete, data: { confirm: t('black_list.label.destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('black_list.action.new'), new_black_list_path %>

app/views/black_lists/new.html.erb
<h1><%= t('black_list.title.new') %></h1>

<%= render 'form' %>

<%= link_to t('application.action.back'), black_lists_path %>

app/views/black_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @black_list.word %>
</p>

<%= link_to t('black_list.action.update'), edit_black_list_path(@black_list) %> |
<%= link_to t('application.action.back'), black_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<dl>
  <dt><%= t('application.menu.description') %></dt>
  <dd><%= link_to t('application.menu.black_list'), black_lists_url %></dd>
  <dd><%= link_to t('application.menu.topic'), topics_url %></dd>
</dl>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, t('application.label.error')) %> <%= t('topic.label.error') %>:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @parent_topic.nil? %>
  <div class="field">
    <%= t('helpers.label.topic.topic') %><br>
    <%= @parent_topic.description %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status, Topic.status_collection) %>
  </div>
    <%= f.hidden_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_item.html.erb
<li>
  <%= topic.description %>

  <%= link_to t('topic.action.reply'), new_child_topic_path(topic.id) %>

<% unless topic.topics.empty? %>
  <ul>
    <%= render partial: "topics/item", collection: FinderTopicService.find_by_topic(topic).where(status: :active), as: :topic %>
  </ul>
<% end %>
</li>

app/views/topics/edit.html.erb
<h1><%= t('topic.title.edit') %></h1>

<%= render 'form' %>

<%= link_to t('application.action.show'), @topic %> |
<%= link_to t('application.action.back'), topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('topic.action.index') %></h1>
<%= link_to t('topic.action.new'), new_topic_path %>

<ul>
<% @topics.each do |t| %>
    <%= render partial: "item", collection: [t], as: :topic %>
<% end %>
</ul>

<%= pagination(@total, @limit, @page) %>

app/views/topics/new.html.erb
<h1><%= t('topic.title.new') %></h1>

<%= render 'form' %>

<%= link_to t('application.action.back'), topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <br>
  <strong><%= t('helpers.label.topic.description') %>:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong><%= t('helpers.label.topic.status') %>:</strong>
  <%= @topic.status %>
</p>

<% unless @topic.topic.nil? %>
<p>
  <strong><%= t('helpers.label.topic.topic') %>:</strong>
  <%= @topic.topic.description %>
</p>
<% end %>

<%= link_to t('application.action.back'), topics_path %>